### ISSUE TITLE
custom headers per route

### ISSUE THREAD

**Issue by YutaUra** [progfay/nextjs-ssg-rewrite-rule-gen#5]
Is add_header supported?

My suggestion would be to use [minimatch](https://www.npmjs.com/package/minimatch) internally to do the following.

```json
{
  "pagesDirPath": "pages",
  "nginxDirectives": {
    "/posts/*": [
      "add_header Cache-Control \"public, max-age=120, must-revalidate\";"
    ],
    "/assets/imgs/**": [
      "add_header Cache-Control \"public, max-age=1200, must-revalidate\";",
      "add_header Something \"else\";"
    ],
  }
}
```

Should Be,

```conf
location ~ ^/?$ {
  rewrite ^/?$ /index.html break;
}

location ~ ^/posts/[^/]+?/?$ {
  add_header Cache-Control "public, max-age=120, must-revalidate";
  rewrite ^/posts/[^/]+?/?$ /posts/[id].html break;
}

location ~ ^/assets/imgs/.+$ {
  add_header Cache-Control "public, max-age=1200, must-revalidate";
  add_header Something "else";
  rewrite ^/assets/imgs/(.+)$ /assets/imgs/$1 break;
}
```

Of course, this does not mean that the actual I/F must be like this, but it would be nice to have a high degree of customizability.

**Comment by progfay** [comment]
@YutaUra Thank you for your contribution!

I create a new PR: https://github.com/progfay/nextjs-ssg-rewrite-rule-gen/pull/7

The new feature "nginxConfigs" config should resolve this issue!

**Comment by progfay** [comment]
Hi, @YutaUra 

I released new version [`@progfay/nextjs-ssg-rewrite-rule-gen@1.1.0`](https://www.npmjs.com/package/@progfay/nextjs-ssg-rewrite-rule-gen/v/1.1.0).

This release includes `"nginxConfigs"` config (#7)!
